### ISSUE TITLE
Would be nice to have setter for Options to change margins dynamically

### ISSUE THREAD

**Issue by Qvatra** [IjzerenHein/famous-boxlayout#1]

**Comment by IjzerenHein** [comment]
This is currently unfortunately not possible, the component would have to be rewritten internally to make this properly possible. It uses multiple FlexibleLayouts internally which are created based on the margins specified in the constructor.

As an alternative you could use a https://github.com/IjzerenHein/famous-flex LayoutController. It is actually more efficient and gives you much more power features. If you just want to use it for margins, you could achieve the same result as BoxLayout using:

``` javascript
function marginateRenderable(renderable, margins) {
  return new LayoutController({
    layoutOptions: {
      layout: GridLayout,
      layoutOptions: {
        cells: [1, 1],
        margins: margins
      }
    },
    dataSource: [
      renderable
    ]
  });
}

var surface = new Surface({});
this.add(marginateRenderable(surface, [10, 20, 30, 10]));
```

**Comment by Qvatra** [comment]
Thx. I think Proportional layout is more appropriate, but I have a problem: I don't know how to set horizontal direction for proportional layout. Any help would be appreciated

var layoutController = new LayoutController({
  layout: ProportionalLayout,
  layoutOptions: {
    ratios: [1, 10, 1],
  },
  dataSource: [
    new Surface({content: 'item 1', properties:{background:'red'}}), 
    new Surface({content: 'item 2', properties:{background:'green'}}),
    new Surface({content: 'item 3', properties:{background:'red'}})
  ]
});

**Comment by IjzerenHein** [comment]
Sure, no problem. You have to specify the `direction` on the layout-controller, like this:

``` javascript
var layoutController = new LayoutController({
  direction: 0,
  ...
});
```

Or use the Direction enum from famo.us Utility: `Utility.Direction.X`

**Comment by Qvatra** [comment]
Great! Thx!
